config/routes.rb
Rails.application.routes.draw do
  resources :drawings
  root to: "drawings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/drawing.rb
class Drawing < ApplicationRecord
  kredis_json :objects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drawings_controller.rb
class DrawingsController < ApplicationController
  before_action :set_drawing, only: %i[ show edit update destroy ]

  # GET /drawings or /drawings.json
  def index
    @drawings = Drawing.all
  end

  # GET /drawings/1 or /drawings/1.json
  def show
  end

  # GET /drawings/new
  def new
    @drawing = Drawing.new
  end

  # GET /drawings/1/edit
  def edit
  end

  # POST /drawings or /drawings.json
  def create
    @drawing = Drawing.new(drawing_params)

    respond_to do |format|
      if @drawing.save
        format.html { redirect_to drawing_url(@drawing), notice: "Drawing was successfully created." }
        format.json { render :show, status: :created, location: @drawing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drawings/1 or /drawings/1.json
  def update
    respond_to do |format|
      if @drawing.update(drawing_params)
        format.html { redirect_to drawing_url(@drawing), notice: "Drawing was successfully updated." }
        format.json { render :show, status: :ok, location: @drawing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @drawing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drawings/1 or /drawings/1.json
  def destroy
    @drawing.destroy

    respond_to do |format|
      format.html { redirect_to drawings_url, notice: "Drawing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_drawing
      @drawing = Drawing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def drawing_params
      params.require(:drawing).permit(:name, :width, :height, :objects)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/drawings/_drawing.html.erb
<div id="<%= dom_id drawing %>">
  <p>
    <strong>Name:</strong>
    <%= drawing.name %>
  </p>

  <p>
    <strong>Width:</strong>
    <%= drawing.width %>
  </p>

  <p>
    <strong>Height:</strong>
    <%= drawing.height %>
  </p>
</div>

app/views/drawings/_form.html.erb
<%= form_with(model: drawing) do |form| %>
  <% if drawing.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(drawing.errors.count, "error") %> prohibited this drawing from being saved:</h2>

      <ul>
        <% drawing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :width, style: "display: block" %>
    <%= form.number_field :width %>
  </div>

  <div>
    <%= form.label :height, style: "display: block" %>
    <%= form.number_field :height %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/drawings/edit.html.erb
<h1>Editing drawing</h1>

<%= render "form", drawing: @drawing %>

<br>

<div>
  <%= link_to "Show this drawing", @drawing %> |
  <%= link_to "Back to drawings", drawings_path %>
</div>

app/views/drawings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Drawings</h1>

<div id="drawings">
  <% @drawings.each do |drawing| %>
    <%= render drawing %>
    <p>
      <%= link_to "Show this drawing", drawing %>
    </p>
  <% end %>
</div>

<%= link_to "New drawing", new_drawing_path %>

app/views/drawings/new.html.erb
<h1>New drawing</h1>

<%= render "form", drawing: @drawing %>

<br>

<div>
  <%= link_to "Back to drawings", drawings_path %>
</div>

app/views/drawings/show.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "controllers/drawing_canvas_controller" %>
  <style>
    div[data-controller="drawing-canvas"] {
      display: flex;
      justify-content: center;
    }

    div[data-controller="drawing-canvas"] canvas {
        border: solid 2px black;
    }
  </style>
<% end %>

<p style="color: green"><%= notice %></p>

<%= render @drawing %>

<div data-controller="drawing-canvas" data-drawing-canvas-drawing-id-value="<%= @drawing.id %>">
  <canvas data-drawing-canvas-target="canvas"
          width="<%= @drawing.width %>"
          height="<%= @drawing.height %>">
  </canvas>
</div>

<div>
  <%= link_to "Edit this drawing", edit_drawing_path(@drawing) %> |
  <%= link_to "Back to drawings", drawings_path %>

  <%= button_to "Destroy this drawing", @drawing, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dcollab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield(:head) if content_for?(:head) %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>